services:
  utils:
    build:
      context: ..
      dockerfile: docker/dockerfiles/Dockerfile.utils
    image: my_utils
    entrypoint: [ "/bin/true" ]

  minio:
    image: minio/minio:latest
    container_name: minio_s3
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - "9000:9000"   # API
      - "9090:9090"   # web UI
    command: server /data --console-address ":9090"

  backend:
    build:
      context: ..
      dockerfile: docker/dockerfiles/Dockerfile.extractor
    container_name: abbreviation_backend
    ports:
      - "8080:8080"
    environment:
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - minio
      - utils

  frontend:
    build:
      context: ..
      dockerfile: docker/dockerfiles/Dockerfile.web
    container_name: abbreviation_frontend
    ports:
      - "8501:8501"
    environment:
      - AES_HOST=http://backend:8080/api/abbrev/extract
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=abbreviation-extractor-web
    depends_on:
      - backend
      - minio
      - utils
