import os

ABBREVIATION_DETECTION_TECH_REPLICAS = int(os.getenv("ABBREVIATION_DETECTION_TECH_REPLICAS", 1))
ABBREVIATION_DETECTOR_REPLICAS = int(os.getenv("ABBREVIATION_DETECTOR_REPLICAS", 1))
EXPANSION_DETECTOR_REPLICAS = int(os.getenv("EXPANSION_DETECTOR_REPLICAS", 1))

ABBREVIATION_EXTRACTOR_MAX_MSG_DATA_BATCH_SIZE = int(os.getenv("ABBREVIATION_EXTRACTOR_MAX_MSG_DATA_BATCH_SIZE", 500))
